### ISSUE TITLE
Fix runner holiday issues

### ISSUE THREAD

**Issue by Geukers** [AlgoETS/BullETS#14]
- [x] Fix holidays returning "Symbol couldn't be found" 
- [x] Fix starting or ending date on a holiday causing an error

If starting date or ending date is on a weekend, the runner will consider the first Monday as the first resolution, and the last Friday as the last resolution. If either of those is on a holiday, this issue still occurs.

**Comment by SamiMammouche** [comment]
Since FMP doesn't provide a reliable endpoint to retrieve holidays (see below), for now I would suggest to skip resolutions where we do not get any data from FMP.

https://financialmodelingprep.com/developer/docs/is-the-market-open only goes back 2 years, whereas historical price can go back 10 years. There are also some dates where FMP doesn't have any data and that are missing from the list.

**Comment by TristanFecteau** [comment]
It does not fail, it just logs that the symbol could not be found since our data source does not have that increment of data, this should be the way to go, we cannot have data that does not exist and cannot list all holidays going back 10 years to skip these increments...
![image](https://user-images.githubusercontent.com/80732570/125012468-411ad500-e038-11eb-9ece-01b340a0f17a.png)

**Comment by space333k** [comment]
It might only go three years in the past because we have the free version, more testing needed
