### ISSUE TITLE
Starting or ending date on weekend causes error

### ISSUE THREAD

**Issue by Geukers** [AlgoETS/BullETS#15]

**Comment by SamiMammouche** [comment]
This issue should be fixed as part of both #13 and #14

**Comment by SamiMammouche** [comment]
Moved the holiday issue to #14, as both holiday issues should be fixed together

**Comment by SamiMammouche** [comment]
After investigation, this is not an issue:
- If the strategy starts on a weekend, no resolution will be performed until Monday.
- If the strategy ends on a weekend, the last resolution will be performed on Friday.

However, if the last resolution is on a Friday and that Friday is a holiday, there will be an error when the portfolio tries to get the final balance. As that issue is related to #14, this one will be closed.
